// Code generated by qtc from "Edit.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vcollection/vitem/Edit.html:2
package vitem

//line views/vcollection/vitem/Edit.html:2
import (
	"github.com/kyleu/todoforge/app"
	"github.com/kyleu/todoforge/app/collection/item"
	"github.com/kyleu/todoforge/app/controller/cutil"
	"github.com/kyleu/todoforge/views/components"
	"github.com/kyleu/todoforge/views/layout"
)

//line views/vcollection/vitem/Edit.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vcollection/vitem/Edit.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vcollection/vitem/Edit.html:10
type Edit struct {
	layout.Basic
	Model *item.Item
	IsNew bool
}

//line views/vcollection/vitem/Edit.html:16
func (p *Edit) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vcollection/vitem/Edit.html:16
	qw422016.N().S(`
  <div class="card">
`)
//line views/vcollection/vitem/Edit.html:18
	if p.IsNew {
//line views/vcollection/vitem/Edit.html:18
		qw422016.N().S(`    <div class="right"><a href="?prototype=random"><button>Random</button></a></div>
    <h3>`)
//line views/vcollection/vitem/Edit.html:20
		components.StreamSVGRefIcon(qw422016, `file`, ps)
//line views/vcollection/vitem/Edit.html:20
		qw422016.N().S(` New Item</h3>
    <form action="/collection/item/_new" class="mt" method="post">
`)
//line views/vcollection/vitem/Edit.html:22
	} else {
//line views/vcollection/vitem/Edit.html:22
		qw422016.N().S(`    <div class="right"><a href="`)
//line views/vcollection/vitem/Edit.html:23
		qw422016.E().S(p.Model.WebPath())
//line views/vcollection/vitem/Edit.html:23
		qw422016.N().S(`/delete" onclick="return confirm('Are you sure you wish to delete item [`)
//line views/vcollection/vitem/Edit.html:23
		qw422016.E().S(p.Model.String())
//line views/vcollection/vitem/Edit.html:23
		qw422016.N().S(`]?')"><button>Delete</button></a></div>
    <h3>`)
//line views/vcollection/vitem/Edit.html:24
		components.StreamSVGRefIcon(qw422016, `file`, ps)
//line views/vcollection/vitem/Edit.html:24
		qw422016.N().S(` Edit Item [`)
//line views/vcollection/vitem/Edit.html:24
		qw422016.E().S(p.Model.String())
//line views/vcollection/vitem/Edit.html:24
		qw422016.N().S(`]</h3>
    <form action="" method="post">
`)
//line views/vcollection/vitem/Edit.html:26
	}
//line views/vcollection/vitem/Edit.html:26
	qw422016.N().S(`      <table class="mt expanded">
        <tbody>
          `)
//line views/vcollection/vitem/Edit.html:29
	if p.IsNew {
//line views/vcollection/vitem/Edit.html:29
		components.StreamTableInputUUID(qw422016, "id", "", "ID", &p.Model.ID, 5, "UUID in format (00000000-0000-0000-0000-000000000000)")
//line views/vcollection/vitem/Edit.html:29
	}
//line views/vcollection/vitem/Edit.html:29
	qw422016.N().S(`
          `)
//line views/vcollection/vitem/Edit.html:30
	components.StreamTableInputUUID(qw422016, "collectionID", "input-collectionID", "Collection ID", &p.Model.CollectionID, 5, "UUID in format (00000000-0000-0000-0000-000000000000)")
//line views/vcollection/vitem/Edit.html:30
	qw422016.N().S(`
          `)
//line views/vcollection/vitem/Edit.html:31
	components.StreamTableInput(qw422016, "name", "", "Name", p.Model.Name, 5, "String text")
//line views/vcollection/vitem/Edit.html:31
	qw422016.N().S(`
          <tr><td colspan="2"><button type="submit">Save Changes</button></td></tr>
        </tbody>
      </table>
    </form>
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      todoforge.autocomplete(document.getElementById("input-collectionID"), "/collection?collection.l=10", "q", (o) => o["name"] + " (" + o["id"] + ")", (o) => o["id"]);
    });
  </script>
`)
//line views/vcollection/vitem/Edit.html:42
}

//line views/vcollection/vitem/Edit.html:42
func (p *Edit) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vcollection/vitem/Edit.html:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vcollection/vitem/Edit.html:42
	p.StreamBody(qw422016, as, ps)
//line views/vcollection/vitem/Edit.html:42
	qt422016.ReleaseWriter(qw422016)
//line views/vcollection/vitem/Edit.html:42
}

//line views/vcollection/vitem/Edit.html:42
func (p *Edit) Body(as *app.State, ps *cutil.PageState) string {
//line views/vcollection/vitem/Edit.html:42
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vcollection/vitem/Edit.html:42
	p.WriteBody(qb422016, as, ps)
//line views/vcollection/vitem/Edit.html:42
	qs422016 := string(qb422016.B)
//line views/vcollection/vitem/Edit.html:42
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vcollection/vitem/Edit.html:42
	return qs422016
//line views/vcollection/vitem/Edit.html:42
}
