// Code generated by qtc from "Edit.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vcollection/vitem/Edit.html:1
package vitem

//line views/vcollection/vitem/Edit.html:1
import (
	"github.com/kyleu/todoforge/app"
	"github.com/kyleu/todoforge/app/collection/item"
	"github.com/kyleu/todoforge/app/controller/cutil"
	"github.com/kyleu/todoforge/app/util"
	"github.com/kyleu/todoforge/views/components"
	"github.com/kyleu/todoforge/views/components/edit"
	"github.com/kyleu/todoforge/views/layout"
)

//line views/vcollection/vitem/Edit.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vcollection/vitem/Edit.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vcollection/vitem/Edit.html:11
type Edit struct {
	layout.Basic
	Model *item.Item
	Paths []string
	IsNew bool
}

//line views/vcollection/vitem/Edit.html:18
func (p *Edit) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vcollection/vitem/Edit.html:18
	qw422016.N().S(`
  <div class="card">
`)
//line views/vcollection/vitem/Edit.html:20
	if p.IsNew {
//line views/vcollection/vitem/Edit.html:20
		qw422016.N().S(`    <div class="right"><a href="?prototype=random"><button>Random</button></a></div>
    <h3>`)
//line views/vcollection/vitem/Edit.html:22
		components.StreamSVGIcon(qw422016, `file`, ps)
//line views/vcollection/vitem/Edit.html:22
		qw422016.N().S(` New Item</h3>
`)
//line views/vcollection/vitem/Edit.html:23
	} else {
//line views/vcollection/vitem/Edit.html:23
		qw422016.N().S(`    <div class="right"><a class="link-confirm" href="`)
//line views/vcollection/vitem/Edit.html:24
		qw422016.E().S(p.Model.WebPath(p.Paths...))
//line views/vcollection/vitem/Edit.html:24
		qw422016.N().S(`/delete" data-message="Are you sure you wish to delete item [`)
//line views/vcollection/vitem/Edit.html:24
		qw422016.E().S(p.Model.String())
//line views/vcollection/vitem/Edit.html:24
		qw422016.N().S(`]?"><button>`)
//line views/vcollection/vitem/Edit.html:24
		components.StreamSVGButton(qw422016, "times", ps)
//line views/vcollection/vitem/Edit.html:24
		qw422016.N().S(` Delete</button></a></div>
    <h3>`)
//line views/vcollection/vitem/Edit.html:25
		components.StreamSVGIcon(qw422016, `file`, ps)
//line views/vcollection/vitem/Edit.html:25
		qw422016.N().S(` Edit Item [`)
//line views/vcollection/vitem/Edit.html:25
		qw422016.E().S(p.Model.String())
//line views/vcollection/vitem/Edit.html:25
		qw422016.N().S(`]</h3>
`)
//line views/vcollection/vitem/Edit.html:26
	}
//line views/vcollection/vitem/Edit.html:26
	qw422016.N().S(`    <form action="`)
//line views/vcollection/vitem/Edit.html:27
	qw422016.E().S(util.Choose(p.IsNew, item.Route(p.Paths...)+`/_new`, p.Model.WebPath(p.Paths...)+`/edit`))
//line views/vcollection/vitem/Edit.html:27
	qw422016.N().S(`" class="mt" method="post">
      <table class="mt expanded">
        <tbody>
          `)
//line views/vcollection/vitem/Edit.html:30
	if p.IsNew {
//line views/vcollection/vitem/Edit.html:30
		edit.StreamUUIDTable(qw422016, "id", "", "ID", &p.Model.ID, 5, "UUID in format (00000000-0000-0000-0000-000000000000)")
//line views/vcollection/vitem/Edit.html:30
	}
//line views/vcollection/vitem/Edit.html:30
	qw422016.N().S(`
          `)
//line views/vcollection/vitem/Edit.html:31
	edit.StreamUUIDTable(qw422016, "collectionID", "input-collectionID", "Collection ID", &p.Model.CollectionID, 5, "UUID in format (00000000-0000-0000-0000-000000000000)")
//line views/vcollection/vitem/Edit.html:31
	qw422016.N().S(`
          `)
//line views/vcollection/vitem/Edit.html:32
	edit.StreamStringTable(qw422016, "name", "", "Name", p.Model.Name, 5, "String text")
//line views/vcollection/vitem/Edit.html:32
	qw422016.N().S(`
          <tr><td colspan="2"><button type="submit">Save Changes</button></td></tr>
        </tbody>
      </table>
    </form>
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      todoforge.autocomplete(document.getElementById("input-collectionID"), "/collection?collection.l=10", "q", (o) => (o["name"] || "[no name]") + " (" + o["id"] + ")", (o) => o["id"]);
    });
  </script>
`)
//line views/vcollection/vitem/Edit.html:43
}

//line views/vcollection/vitem/Edit.html:43
func (p *Edit) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vcollection/vitem/Edit.html:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vcollection/vitem/Edit.html:43
	p.StreamBody(qw422016, as, ps)
//line views/vcollection/vitem/Edit.html:43
	qt422016.ReleaseWriter(qw422016)
//line views/vcollection/vitem/Edit.html:43
}

//line views/vcollection/vitem/Edit.html:43
func (p *Edit) Body(as *app.State, ps *cutil.PageState) string {
//line views/vcollection/vitem/Edit.html:43
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vcollection/vitem/Edit.html:43
	p.WriteBody(qb422016, as, ps)
//line views/vcollection/vitem/Edit.html:43
	qs422016 := string(qb422016.B)
//line views/vcollection/vitem/Edit.html:43
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vcollection/vitem/Edit.html:43
	return qs422016
//line views/vcollection/vitem/Edit.html:43
}
