// Code generated by qtc from "About.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/About.html:1
package views

//line views/About.html:1
import (
	"time"

	"github.com/kyleu/todoforge/app"
	"github.com/kyleu/todoforge/app/controller/cutil"
	"github.com/kyleu/todoforge/app/util"
	"github.com/kyleu/todoforge/views/components"
	"github.com/kyleu/todoforge/views/components/view"
	"github.com/kyleu/todoforge/views/layout"
)

//line views/About.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/About.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/About.html:12
type About struct {
	layout.Basic
	Version string
	Started time.Time
}

//line views/About.html:18
func (p *About) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/About.html:18
	qw422016.N().S(`
  <div class="card">
    <h3>`)
//line views/About.html:20
	components.StreamSVGIcon(qw422016, `app`, ps)
//line views/About.html:20
	qw422016.N().S(` `)
//line views/About.html:20
	qw422016.E().S(util.AppName)
//line views/About.html:20
	qw422016.N().S(`</h3>
    <em>v`)
//line views/About.html:21
	qw422016.E().S(p.Version)
//line views/About.html:21
	qw422016.N().S(`, started `)
//line views/About.html:21
	view.StreamTimestampRelative(qw422016, &p.Started, false)
//line views/About.html:21
	qw422016.N().S(`</em>
  </div>
  <div class="card">
    <h3>About</h3>
    <p>Coming soon...</p>
  </div>
  `)
//line views/About.html:27
	StreamSourceCode(qw422016)
//line views/About.html:27
	qw422016.N().S(`
  `)
//line views/About.html:28
	StreamFeedback(qw422016)
//line views/About.html:28
	qw422016.N().S(`
`)
//line views/About.html:29
}

//line views/About.html:29
func (p *About) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/About.html:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/About.html:29
	p.StreamBody(qw422016, as, ps)
//line views/About.html:29
	qt422016.ReleaseWriter(qw422016)
//line views/About.html:29
}

//line views/About.html:29
func (p *About) Body(as *app.State, ps *cutil.PageState) string {
//line views/About.html:29
	qb422016 := qt422016.AcquireByteBuffer()
//line views/About.html:29
	p.WriteBody(qb422016, as, ps)
//line views/About.html:29
	qs422016 := string(qb422016.B)
//line views/About.html:29
	qt422016.ReleaseByteBuffer(qb422016)
//line views/About.html:29
	return qs422016
//line views/About.html:29
}

//line views/About.html:31
func StreamSourceCode(qw422016 *qt422016.Writer) {
//line views/About.html:31
	qw422016.N().S(`
  <div class="card">
    <h3>Source Code</h3>
    <p>The project is available on <a href="https://github.com/kyleu/todoforge" target="_blank" rel="noopener noreferrer">GitHub</a></p>
  </div>
`)
//line views/About.html:36
}

//line views/About.html:36
func WriteSourceCode(qq422016 qtio422016.Writer) {
//line views/About.html:36
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/About.html:36
	StreamSourceCode(qw422016)
//line views/About.html:36
	qt422016.ReleaseWriter(qw422016)
//line views/About.html:36
}

//line views/About.html:36
func SourceCode() string {
//line views/About.html:36
	qb422016 := qt422016.AcquireByteBuffer()
//line views/About.html:36
	WriteSourceCode(qb422016)
//line views/About.html:36
	qs422016 := string(qb422016.B)
//line views/About.html:36
	qt422016.ReleaseByteBuffer(qb422016)
//line views/About.html:36
	return qs422016
//line views/About.html:36
}

//line views/About.html:38
func StreamFeedback(qw422016 *qt422016.Writer) {
//line views/About.html:38
	qw422016.N().S(`
  <div class="card">
    <h3>Feedback</h3>
    <p>For now, email <a href="mailto:todoforge@kyleu.com">Kyle U</a></p>
  </div>
`)
//line views/About.html:43
}

//line views/About.html:43
func WriteFeedback(qq422016 qtio422016.Writer) {
//line views/About.html:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/About.html:43
	StreamFeedback(qw422016)
//line views/About.html:43
	qt422016.ReleaseWriter(qw422016)
//line views/About.html:43
}

//line views/About.html:43
func Feedback() string {
//line views/About.html:43
	qb422016 := qt422016.AcquireByteBuffer()
//line views/About.html:43
	WriteFeedback(qb422016)
//line views/About.html:43
	qs422016 := string(qb422016.B)
//line views/About.html:43
	qt422016.ReleaseByteBuffer(qb422016)
//line views/About.html:43
	return qs422016
//line views/About.html:43
}
