-- {% func DropAll() %}
-- {%= ItemDrop() %}
-- {%= CollectionDrop() %}
-- {%= AuditDrop() %}
-- {% endfunc %}

-- {% func CreateAll() %}
-- {%= AuditCreate() %}
-- {%= CollectionCreate() %}
-- {%= ItemCreate() %}
-- {% endfunc %}
