// Code generated by qtc from "collection.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/ddl/collection.sql:1
package ddl

//line queries/ddl/collection.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/collection.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/collection.sql:1
func StreamCollectionDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/collection.sql:1
	qw422016.N().S(`
drop table if exists "collection";
-- `)
//line queries/ddl/collection.sql:3
}

//line queries/ddl/collection.sql:3
func WriteCollectionDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/collection.sql:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/collection.sql:3
	StreamCollectionDrop(qw422016)
//line queries/ddl/collection.sql:3
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/collection.sql:3
}

//line queries/ddl/collection.sql:3
func CollectionDrop() string {
//line queries/ddl/collection.sql:3
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/collection.sql:3
	WriteCollectionDrop(qb422016)
//line queries/ddl/collection.sql:3
	qs422016 := string(qb422016.B)
//line queries/ddl/collection.sql:3
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/collection.sql:3
	return qs422016
//line queries/ddl/collection.sql:3
}

// --

//line queries/ddl/collection.sql:5
func StreamCollectionCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/collection.sql:5
	qw422016.N().S(`
create table if not exists "collection" (
  "id" uuid not null,
  "name" text not null,
  "created" timestamp not null default current_timestamp,
  primary key ("id")
);
-- `)
//line queries/ddl/collection.sql:12
}

//line queries/ddl/collection.sql:12
func WriteCollectionCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/collection.sql:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/collection.sql:12
	StreamCollectionCreate(qw422016)
//line queries/ddl/collection.sql:12
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/collection.sql:12
}

//line queries/ddl/collection.sql:12
func CollectionCreate() string {
//line queries/ddl/collection.sql:12
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/collection.sql:12
	WriteCollectionCreate(qb422016)
//line queries/ddl/collection.sql:12
	qs422016 := string(qb422016.B)
//line queries/ddl/collection.sql:12
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/collection.sql:12
	return qs422016
//line queries/ddl/collection.sql:12
}
