// Code generated by qtc from "collection.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/ddl/collection.sql:2
package ddl

//line queries/ddl/collection.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/collection.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/collection.sql:2
func StreamCollectionDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/collection.sql:2
	qw422016.N().S(`
drop table if exists "collection";
-- `)
//line queries/ddl/collection.sql:4
}

//line queries/ddl/collection.sql:4
func WriteCollectionDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/collection.sql:4
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/collection.sql:4
	StreamCollectionDrop(qw422016)
//line queries/ddl/collection.sql:4
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/collection.sql:4
}

//line queries/ddl/collection.sql:4
func CollectionDrop() string {
//line queries/ddl/collection.sql:4
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/collection.sql:4
	WriteCollectionDrop(qb422016)
//line queries/ddl/collection.sql:4
	qs422016 := string(qb422016.B)
//line queries/ddl/collection.sql:4
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/collection.sql:4
	return qs422016
//line queries/ddl/collection.sql:4
}

// --

//line queries/ddl/collection.sql:6
func StreamCollectionCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/collection.sql:6
	qw422016.N().S(`
create table if not exists "collection" (
  "id" uuid not null,
  "name" text not null,
  "created" timestamp not null default current_timestamp,
  primary key ("id")
);
-- `)
//line queries/ddl/collection.sql:13
}

//line queries/ddl/collection.sql:13
func WriteCollectionCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/collection.sql:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/collection.sql:13
	StreamCollectionCreate(qw422016)
//line queries/ddl/collection.sql:13
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/collection.sql:13
}

//line queries/ddl/collection.sql:13
func CollectionCreate() string {
//line queries/ddl/collection.sql:13
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/collection.sql:13
	WriteCollectionCreate(qb422016)
//line queries/ddl/collection.sql:13
	qs422016 := string(qb422016.B)
//line queries/ddl/collection.sql:13
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/collection.sql:13
	return qs422016
//line queries/ddl/collection.sql:13
}
