// Code generated by qtc from "item.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/ddl/item.sql:1
package ddl

//line queries/ddl/item.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/item.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/item.sql:1
func StreamItemDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/item.sql:1
	qw422016.N().S(`
drop table if exists "item";
-- `)
//line queries/ddl/item.sql:3
}

//line queries/ddl/item.sql:3
func WriteItemDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/item.sql:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/item.sql:3
	StreamItemDrop(qw422016)
//line queries/ddl/item.sql:3
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/item.sql:3
}

//line queries/ddl/item.sql:3
func ItemDrop() string {
//line queries/ddl/item.sql:3
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/item.sql:3
	WriteItemDrop(qb422016)
//line queries/ddl/item.sql:3
	qs422016 := string(qb422016.B)
//line queries/ddl/item.sql:3
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/item.sql:3
	return qs422016
//line queries/ddl/item.sql:3
}

// --

//line queries/ddl/item.sql:5
func StreamItemCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/item.sql:5
	qw422016.N().S(`
create table if not exists "item" (
  "id" uuid not null,
  "collection_id" uuid not null,
  "name" text not null,
  "created" timestamp not null default current_timestamp,
  foreign key ("collection_id") references "collection" ("id"),
  primary key ("id")
);

create index if not exists "item__collection_id_idx" on "item" ("collection_id");
-- `)
//line queries/ddl/item.sql:16
}

//line queries/ddl/item.sql:16
func WriteItemCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/item.sql:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/item.sql:16
	StreamItemCreate(qw422016)
//line queries/ddl/item.sql:16
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/item.sql:16
}

//line queries/ddl/item.sql:16
func ItemCreate() string {
//line queries/ddl/item.sql:16
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/item.sql:16
	WriteItemCreate(qb422016)
//line queries/ddl/item.sql:16
	qs422016 := string(qb422016.B)
//line queries/ddl/item.sql:16
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/item.sql:16
	return qs422016
//line queries/ddl/item.sql:16
}
