// Code generated by qtc from "item.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/ddl/item.sql:2
package ddl

//line queries/ddl/item.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/ddl/item.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/ddl/item.sql:2
func StreamItemDrop(qw422016 *qt422016.Writer) {
//line queries/ddl/item.sql:2
	qw422016.N().S(`
drop table if exists "item";
-- `)
//line queries/ddl/item.sql:4
}

//line queries/ddl/item.sql:4
func WriteItemDrop(qq422016 qtio422016.Writer) {
//line queries/ddl/item.sql:4
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/item.sql:4
	StreamItemDrop(qw422016)
//line queries/ddl/item.sql:4
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/item.sql:4
}

//line queries/ddl/item.sql:4
func ItemDrop() string {
//line queries/ddl/item.sql:4
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/item.sql:4
	WriteItemDrop(qb422016)
//line queries/ddl/item.sql:4
	qs422016 := string(qb422016.B)
//line queries/ddl/item.sql:4
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/item.sql:4
	return qs422016
//line queries/ddl/item.sql:4
}

// --

//line queries/ddl/item.sql:6
func StreamItemCreate(qw422016 *qt422016.Writer) {
//line queries/ddl/item.sql:6
	qw422016.N().S(`
create table if not exists "item" (
  "id" uuid not null,
  "collection_id" uuid not null,
  "name" text not null,
  "created" timestamp not null default current_timestamp,
  foreign key ("collection_id") references "collection" ("id"),
  primary key ("id")
);

create index if not exists "item__collection_id_idx" on "item" ("collection_id");
-- `)
//line queries/ddl/item.sql:17
}

//line queries/ddl/item.sql:17
func WriteItemCreate(qq422016 qtio422016.Writer) {
//line queries/ddl/item.sql:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/ddl/item.sql:17
	StreamItemCreate(qw422016)
//line queries/ddl/item.sql:17
	qt422016.ReleaseWriter(qw422016)
//line queries/ddl/item.sql:17
}

//line queries/ddl/item.sql:17
func ItemCreate() string {
//line queries/ddl/item.sql:17
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/ddl/item.sql:17
	WriteItemCreate(qb422016)
//line queries/ddl/item.sql:17
	qs422016 := string(qb422016.B)
//line queries/ddl/item.sql:17
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/ddl/item.sql:17
	return qs422016
//line queries/ddl/item.sql:17
}
