// Code generated by qtc from "seed_item.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/seeddata/seed_item.sql:1
package seeddata

//line queries/seeddata/seed_item.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/seeddata/seed_item.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/seeddata/seed_item.sql:1
func StreamItemSeedData(qw422016 *qt422016.Writer) {
//line queries/seeddata/seed_item.sql:1
	qw422016.N().S(`
insert into "item" (
  "id", "collection_id", "name", "created"
) values (
  '10000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000000', 'Test Item', current_timestamp
) on conflict do nothing;
-- `)
//line queries/seeddata/seed_item.sql:7
}

//line queries/seeddata/seed_item.sql:7
func WriteItemSeedData(qq422016 qtio422016.Writer) {
//line queries/seeddata/seed_item.sql:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/seeddata/seed_item.sql:7
	StreamItemSeedData(qw422016)
//line queries/seeddata/seed_item.sql:7
	qt422016.ReleaseWriter(qw422016)
//line queries/seeddata/seed_item.sql:7
}

//line queries/seeddata/seed_item.sql:7
func ItemSeedData() string {
//line queries/seeddata/seed_item.sql:7
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/seeddata/seed_item.sql:7
	WriteItemSeedData(qb422016)
//line queries/seeddata/seed_item.sql:7
	qs422016 := string(qb422016.B)
//line queries/seeddata/seed_item.sql:7
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/seeddata/seed_item.sql:7
	return qs422016
//line queries/seeddata/seed_item.sql:7
}
