// Code generated by qtc from "SizeInfo.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// -- Content managed by Project Forge, see [projectforge.md] for details.
// --

//line queries/schema/SizeInfo.sql:2
package schema

//line queries/schema/SizeInfo.sql:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/schema/SizeInfo.sql:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/schema/SizeInfo.sql:2
func StreamSizeInfo(qw422016 *qt422016.Writer) {
//line queries/schema/SizeInfo.sql:2
	qw422016.N().S(`
select
  'default' as "table_schema",
  "name" as "table_name",
  0 as "row_estimate",
  0 as "total",
  '' as "total_pretty",
  0 as "index",
  '' as "index_pretty",
  0 as "toast",
  '' as "toast_pretty",
  0 as "table",
  '' as "table_pretty"
from "sqlite_master"
where "type" = 'table'
order by "table_name";
-- `)
//line queries/schema/SizeInfo.sql:18
}

//line queries/schema/SizeInfo.sql:18
func WriteSizeInfo(qq422016 qtio422016.Writer) {
//line queries/schema/SizeInfo.sql:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/schema/SizeInfo.sql:18
	StreamSizeInfo(qw422016)
//line queries/schema/SizeInfo.sql:18
	qt422016.ReleaseWriter(qw422016)
//line queries/schema/SizeInfo.sql:18
}

//line queries/schema/SizeInfo.sql:18
func SizeInfo() string {
//line queries/schema/SizeInfo.sql:18
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/schema/SizeInfo.sql:18
	WriteSizeInfo(qb422016)
//line queries/schema/SizeInfo.sql:18
	qs422016 := string(qb422016.B)
//line queries/schema/SizeInfo.sql:18
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/schema/SizeInfo.sql:18
	return qs422016
//line queries/schema/SizeInfo.sql:18
}
