// Code generated by qtc from "SizeInfo.sql". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// --

//line queries/schema/SizeInfo.sql:1
package schema

//line queries/schema/SizeInfo.sql:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line queries/schema/SizeInfo.sql:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line queries/schema/SizeInfo.sql:1
func StreamSizeInfo(qw422016 *qt422016.Writer, dbType string) {
//line queries/schema/SizeInfo.sql:1
	qw422016.N().S(`
-- `)
//line queries/schema/SizeInfo.sql:2
	switch dbType {
	// --

//line queries/schema/SizeInfo.sql:3
	case "sqlite":
//line queries/schema/SizeInfo.sql:3
		qw422016.N().S(`
select
  'default' as "table_schema",
  "name" as "table_name",
  0 as "row_estimate",
  0 as "total",
  '' as "total_pretty",
  0 as "index",
  '' as "index_pretty",
  0 as "toast",
  '' as "toast_pretty",
  0 as "table",
  '' as "table_pretty"
from "sqlite_master"
where "type" = 'table'
order by "table_name";
-- `)
//line queries/schema/SizeInfo.sql:19
	default:
//line queries/schema/SizeInfo.sql:19
		qw422016.N().S(`
select 'unhandled database type [`)
//line queries/schema/SizeInfo.sql:20
		qw422016.E().S(dbType)
//line queries/schema/SizeInfo.sql:20
		qw422016.N().S(`]';
-- `)
//line queries/schema/SizeInfo.sql:21
	}
//line queries/schema/SizeInfo.sql:21
	qw422016.N().S(`
-- `)
//line queries/schema/SizeInfo.sql:22
}

//line queries/schema/SizeInfo.sql:22
func WriteSizeInfo(qq422016 qtio422016.Writer, dbType string) {
//line queries/schema/SizeInfo.sql:22
	qw422016 := qt422016.AcquireWriter(qq422016)
//line queries/schema/SizeInfo.sql:22
	StreamSizeInfo(qw422016, dbType)
//line queries/schema/SizeInfo.sql:22
	qt422016.ReleaseWriter(qw422016)
//line queries/schema/SizeInfo.sql:22
}

//line queries/schema/SizeInfo.sql:22
func SizeInfo(dbType string) string {
//line queries/schema/SizeInfo.sql:22
	qb422016 := qt422016.AcquireByteBuffer()
//line queries/schema/SizeInfo.sql:22
	WriteSizeInfo(qb422016, dbType)
//line queries/schema/SizeInfo.sql:22
	qs422016 := string(qb422016.B)
//line queries/schema/SizeInfo.sql:22
	qt422016.ReleaseByteBuffer(qb422016)
//line queries/schema/SizeInfo.sql:22
	return qs422016
//line queries/schema/SizeInfo.sql:22
}
