// Code generated by qtc from "Edit.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vcollection/Edit.html:2
package vcollection

//line views/vcollection/Edit.html:2
import (
	"github.com/kyleu/todoforge/app"
	"github.com/kyleu/todoforge/app/collection"
	"github.com/kyleu/todoforge/app/controller/cutil"
	"github.com/kyleu/todoforge/views/components"
	"github.com/kyleu/todoforge/views/components/edit"
	"github.com/kyleu/todoforge/views/layout"
)

//line views/vcollection/Edit.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vcollection/Edit.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vcollection/Edit.html:11
type Edit struct {
	layout.Basic
	Model *collection.Collection
	IsNew bool
}

//line views/vcollection/Edit.html:17
func (p *Edit) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vcollection/Edit.html:17
	qw422016.N().S(`
  <div class="card">
`)
//line views/vcollection/Edit.html:19
	if p.IsNew {
//line views/vcollection/Edit.html:19
		qw422016.N().S(`    <div class="right"><a href="?prototype=random"><button>Random</button></a></div>
    <h3>`)
//line views/vcollection/Edit.html:21
		components.StreamSVGRefIcon(qw422016, `archive`, ps)
//line views/vcollection/Edit.html:21
		qw422016.N().S(` New Collection</h3>
    <form action="/collection/_new" class="mt" method="post">
`)
//line views/vcollection/Edit.html:23
	} else {
//line views/vcollection/Edit.html:23
		qw422016.N().S(`    <div class="right"><a class="link-confirm" href="`)
//line views/vcollection/Edit.html:24
		qw422016.E().S(p.Model.WebPath())
//line views/vcollection/Edit.html:24
		qw422016.N().S(`/delete" data-message="Are you sure you wish to delete collection [`)
//line views/vcollection/Edit.html:24
		qw422016.E().S(p.Model.String())
//line views/vcollection/Edit.html:24
		qw422016.N().S(`]?"><button>Delete</button></a></div>
    <h3>`)
//line views/vcollection/Edit.html:25
		components.StreamSVGRefIcon(qw422016, `archive`, ps)
//line views/vcollection/Edit.html:25
		qw422016.N().S(` Edit Collection [`)
//line views/vcollection/Edit.html:25
		qw422016.E().S(p.Model.String())
//line views/vcollection/Edit.html:25
		qw422016.N().S(`]</h3>
    <form action="" method="post">
`)
//line views/vcollection/Edit.html:27
	}
//line views/vcollection/Edit.html:27
	qw422016.N().S(`      <table class="mt expanded">
        <tbody>
          `)
//line views/vcollection/Edit.html:30
	if p.IsNew {
//line views/vcollection/Edit.html:30
		edit.StreamUUIDTable(qw422016, "id", "", "ID", &p.Model.ID, 5, "UUID in format (00000000-0000-0000-0000-000000000000)")
//line views/vcollection/Edit.html:30
	}
//line views/vcollection/Edit.html:30
	qw422016.N().S(`
          `)
//line views/vcollection/Edit.html:31
	edit.StreamStringTable(qw422016, "name", "", "Name", p.Model.Name, 5, "String text")
//line views/vcollection/Edit.html:31
	qw422016.N().S(`
          <tr><td colspan="2"><button type="submit">Save Changes</button></td></tr>
        </tbody>
      </table>
    </form>
  </div>
`)
//line views/vcollection/Edit.html:37
}

//line views/vcollection/Edit.html:37
func (p *Edit) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vcollection/Edit.html:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vcollection/Edit.html:37
	p.StreamBody(qw422016, as, ps)
//line views/vcollection/Edit.html:37
	qt422016.ReleaseWriter(qw422016)
//line views/vcollection/Edit.html:37
}

//line views/vcollection/Edit.html:37
func (p *Edit) Body(as *app.State, ps *cutil.PageState) string {
//line views/vcollection/Edit.html:37
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vcollection/Edit.html:37
	p.WriteBody(qb422016, as, ps)
//line views/vcollection/Edit.html:37
	qs422016 := string(qb422016.B)
//line views/vcollection/Edit.html:37
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vcollection/Edit.html:37
	return qs422016
//line views/vcollection/Edit.html:37
}
