// Code generated by qtc from "Detail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vaudit/Detail.html:2
package vaudit

//line views/vaudit/Detail.html:2
import (
	"github.com/kyleu/todoforge/app"
	"github.com/kyleu/todoforge/app/controller/cutil"
	"github.com/kyleu/todoforge/app/lib/audit"
	"github.com/kyleu/todoforge/app/lib/filter"
	"github.com/kyleu/todoforge/views/components"
	"github.com/kyleu/todoforge/views/components/view"
	"github.com/kyleu/todoforge/views/layout"
)

//line views/vaudit/Detail.html:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vaudit/Detail.html:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vaudit/Detail.html:12
type Detail struct {
	layout.Basic
	Model   *audit.Audit
	Params  filter.ParamSet
	Records audit.Records
}

//line views/vaudit/Detail.html:19
func (p *Detail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudit/Detail.html:19
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-audit"><button type="button">JSON</button></a>
      <a href="`)
//line views/vaudit/Detail.html:23
	qw422016.E().S(p.Model.WebPath())
//line views/vaudit/Detail.html:23
	qw422016.N().S(`/edit"><button>Edit</button></a>
    </div>
    <h3>`)
//line views/vaudit/Detail.html:25
	components.StreamSVGIcon(qw422016, `cog`, ps)
//line views/vaudit/Detail.html:25
	qw422016.N().S(`Audit [`)
//line views/vaudit/Detail.html:25
	qw422016.E().S(p.Model.String())
//line views/vaudit/Detail.html:25
	qw422016.N().S(`]</h3>
    <div class="overflow full-width">
      <table class="mt">
        <tbody>
          <tr>
            <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
            <td>`)
//line views/vaudit/Detail.html:31
	view.StreamUUID(qw422016, &p.Model.ID)
//line views/vaudit/Detail.html:31
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">App</th>
            <td>`)
//line views/vaudit/Detail.html:35
	qw422016.E().S(p.Model.App)
//line views/vaudit/Detail.html:35
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Act</th>
            <td>`)
//line views/vaudit/Detail.html:39
	qw422016.E().S(p.Model.Act)
//line views/vaudit/Detail.html:39
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Client</th>
            <td>`)
//line views/vaudit/Detail.html:43
	qw422016.E().S(p.Model.Client)
//line views/vaudit/Detail.html:43
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Server</th>
            <td>`)
//line views/vaudit/Detail.html:47
	qw422016.E().S(p.Model.Server)
//line views/vaudit/Detail.html:47
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">User</th>
            <td>`)
//line views/vaudit/Detail.html:51
	qw422016.E().S(p.Model.User)
//line views/vaudit/Detail.html:51
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="JSON object">Metadata</th>
            <td>`)
//line views/vaudit/Detail.html:55
	components.StreamJSON(qw422016, p.Model.Metadata)
//line views/vaudit/Detail.html:55
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Message</th>
            <td>`)
//line views/vaudit/Detail.html:59
	qw422016.E().S(p.Model.Message)
//line views/vaudit/Detail.html:59
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="Date and time, in almost any format">Started</th>
            <td>`)
//line views/vaudit/Detail.html:63
	view.StreamTimestamp(qw422016, &p.Model.Started)
//line views/vaudit/Detail.html:63
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="Date and time, in almost any format">Completed</th>
            <td>`)
//line views/vaudit/Detail.html:67
	view.StreamTimestamp(qw422016, &p.Model.Completed)
//line views/vaudit/Detail.html:67
	qw422016.N().S(`</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
`)
//line views/vaudit/Detail.html:75
	if len(p.Records) > 0 {
//line views/vaudit/Detail.html:75
		qw422016.N().S(`  <div class="card">
    <h3>`)
//line views/vaudit/Detail.html:77
		components.StreamSVGIcon(qw422016, `cog`, ps)
//line views/vaudit/Detail.html:77
		qw422016.N().S(`Audit Records</h3>
    `)
//line views/vaudit/Detail.html:78
		StreamRecordTable(qw422016, p.Records, p.Params, as, ps)
//line views/vaudit/Detail.html:78
		qw422016.N().S(`
  </div>
`)
//line views/vaudit/Detail.html:80
	}
//line views/vaudit/Detail.html:80
	qw422016.N().S(`  `)
//line views/vaudit/Detail.html:81
	components.StreamJSONModal(qw422016, "audit", "Audit JSON", p.Model, 1)
//line views/vaudit/Detail.html:81
	qw422016.N().S(`
`)
//line views/vaudit/Detail.html:82
}

//line views/vaudit/Detail.html:82
func (p *Detail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudit/Detail.html:82
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vaudit/Detail.html:82
	p.StreamBody(qw422016, as, ps)
//line views/vaudit/Detail.html:82
	qt422016.ReleaseWriter(qw422016)
//line views/vaudit/Detail.html:82
}

//line views/vaudit/Detail.html:82
func (p *Detail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vaudit/Detail.html:82
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vaudit/Detail.html:82
	p.WriteBody(qb422016, as, ps)
//line views/vaudit/Detail.html:82
	qs422016 := string(qb422016.B)
//line views/vaudit/Detail.html:82
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vaudit/Detail.html:82
	return qs422016
//line views/vaudit/Detail.html:82
}
