// Code generated by qtc from "List.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!-- Content managed by Project Forge, see [projectforge.md] for details. -->

//line views/vaudit/List.html:2
package vaudit

//line views/vaudit/List.html:2
import (
	"github.com/kyleu/todoforge/app"
	"github.com/kyleu/todoforge/app/controller/cutil"
	"github.com/kyleu/todoforge/app/lib/audit"
	"github.com/kyleu/todoforge/app/lib/filter"
	"github.com/kyleu/todoforge/views/components"
	"github.com/kyleu/todoforge/views/layout"
)

//line views/vaudit/List.html:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vaudit/List.html:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vaudit/List.html:11
type List struct {
	layout.Basic
	Models audit.Audits
	Params filter.ParamSet
}

//line views/vaudit/List.html:17
func (p *List) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudit/List.html:17
	qw422016.N().S(`
  <div class="card">
    <div class="right"><a href="/admin/audit/new"><button>New</button></a></div>
    <h3>`)
//line views/vaudit/List.html:20
	components.StreamSVGRefIcon(qw422016, `cog`, ps)
//line views/vaudit/List.html:20
	qw422016.N().S(` Audits</h3>
`)
//line views/vaudit/List.html:21
	if len(p.Models) == 0 {
//line views/vaudit/List.html:21
		qw422016.N().S(`    <div class="mt"><em>No audits available</em></div>
`)
//line views/vaudit/List.html:23
	} else {
//line views/vaudit/List.html:23
		qw422016.N().S(`    `)
//line views/vaudit/List.html:24
		StreamTable(qw422016, p.Models, p.Params, as, ps)
//line views/vaudit/List.html:24
		qw422016.N().S(`
`)
//line views/vaudit/List.html:25
	}
//line views/vaudit/List.html:25
	qw422016.N().S(`  </div>
`)
//line views/vaudit/List.html:27
}

//line views/vaudit/List.html:27
func (p *List) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudit/List.html:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vaudit/List.html:27
	p.StreamBody(qw422016, as, ps)
//line views/vaudit/List.html:27
	qt422016.ReleaseWriter(qw422016)
//line views/vaudit/List.html:27
}

//line views/vaudit/List.html:27
func (p *List) Body(as *app.State, ps *cutil.PageState) string {
//line views/vaudit/List.html:27
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vaudit/List.html:27
	p.WriteBody(qb422016, as, ps)
//line views/vaudit/List.html:27
	qs422016 := string(qb422016.B)
//line views/vaudit/List.html:27
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vaudit/List.html:27
	return qs422016
//line views/vaudit/List.html:27
}
