// Code generated by qtc from "RecordDetail.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/vaudit/RecordDetail.html:1
package vaudit

//line views/vaudit/RecordDetail.html:1
import (
	"github.com/kyleu/todoforge/app"
	"github.com/kyleu/todoforge/app/controller/cutil"
	"github.com/kyleu/todoforge/app/lib/audit"
	"github.com/kyleu/todoforge/views/components"
	"github.com/kyleu/todoforge/views/components/view"
	"github.com/kyleu/todoforge/views/layout"
)

//line views/vaudit/RecordDetail.html:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/vaudit/RecordDetail.html:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/vaudit/RecordDetail.html:10
type RecordDetail struct {
	layout.Basic
	Model *audit.Record
	Audit *audit.Audit
}

//line views/vaudit/RecordDetail.html:16
func (p *RecordDetail) StreamBody(qw422016 *qt422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudit/RecordDetail.html:16
	qw422016.N().S(`
  <div class="card">
    <div class="right">
      <a href="#modal-record"><button type="button">JSON</button></a>
      <a href="`)
//line views/vaudit/RecordDetail.html:20
	qw422016.E().S(p.Model.WebPath())
//line views/vaudit/RecordDetail.html:20
	qw422016.N().S(`/edit"><button>Edit</button></a>
    </div>
    <h3>`)
//line views/vaudit/RecordDetail.html:22
	components.StreamSVGIcon(qw422016, `cog`, ps)
//line views/vaudit/RecordDetail.html:22
	qw422016.N().S(` Audit Record [`)
//line views/vaudit/RecordDetail.html:22
	qw422016.E().S(p.Model.String())
//line views/vaudit/RecordDetail.html:22
	qw422016.N().S(`]</h3>
    <div class="overflow full-width">
      <table class="mt">
        <tbody>
          <tr>
            <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">ID</th>
            <td>`)
//line views/vaudit/RecordDetail.html:28
	view.StreamUUID(qw422016, &p.Model.ID)
//line views/vaudit/RecordDetail.html:28
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="UUID in format (00000000-0000-0000-0000-000000000000)">Audit ID</th>
            <td>
              <div class="icon">`)
//line views/vaudit/RecordDetail.html:33
	view.StreamUUID(qw422016, &p.Model.AuditID)
//line views/vaudit/RecordDetail.html:33
	qw422016.N().S(`</div>
              <a title="Audit" href="`)
//line views/vaudit/RecordDetail.html:34
	qw422016.E().S(`/admin/audit` + `/` + p.Model.AuditID.String())
//line views/vaudit/RecordDetail.html:34
	qw422016.N().S(`">`)
//line views/vaudit/RecordDetail.html:34
	components.StreamSVGIcon(qw422016, "cog", ps)
//line views/vaudit/RecordDetail.html:34
	qw422016.N().S(`</a>
            </td>
          </tr>
          <tr>
            <th class="shrink" title="String text">T</th>
            <td>`)
//line views/vaudit/RecordDetail.html:39
	qw422016.E().S(p.Model.T)
//line views/vaudit/RecordDetail.html:39
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="String text">Pk</th>
            <td>`)
//line views/vaudit/RecordDetail.html:43
	qw422016.E().S(p.Model.PK)
//line views/vaudit/RecordDetail.html:43
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="JSON object">Changes</th>
            <td>`)
//line views/vaudit/RecordDetail.html:47
	view.StreamDiffs(qw422016, p.Model.Changes)
//line views/vaudit/RecordDetail.html:47
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="JSON object">Metadata</th>
            <td>`)
//line views/vaudit/RecordDetail.html:51
	components.StreamJSON(qw422016, p.Model.Metadata)
//line views/vaudit/RecordDetail.html:51
	qw422016.N().S(`</td>
          </tr>
          <tr>
            <th class="shrink" title="Date and time, in almost any format">Occurred</th>
            <td>`)
//line views/vaudit/RecordDetail.html:55
	view.StreamTimestamp(qw422016, &p.Model.Occurred)
//line views/vaudit/RecordDetail.html:55
	qw422016.N().S(`</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
`)
//line views/vaudit/RecordDetail.html:62
	qw422016.N().S(`  `)
//line views/vaudit/RecordDetail.html:63
	components.StreamJSONModal(qw422016, "record", "Audit Record JSON", p.Model, 1)
//line views/vaudit/RecordDetail.html:63
	qw422016.N().S(`
`)
//line views/vaudit/RecordDetail.html:64
}

//line views/vaudit/RecordDetail.html:64
func (p *RecordDetail) WriteBody(qq422016 qtio422016.Writer, as *app.State, ps *cutil.PageState) {
//line views/vaudit/RecordDetail.html:64
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/vaudit/RecordDetail.html:64
	p.StreamBody(qw422016, as, ps)
//line views/vaudit/RecordDetail.html:64
	qt422016.ReleaseWriter(qw422016)
//line views/vaudit/RecordDetail.html:64
}

//line views/vaudit/RecordDetail.html:64
func (p *RecordDetail) Body(as *app.State, ps *cutil.PageState) string {
//line views/vaudit/RecordDetail.html:64
	qb422016 := qt422016.AcquireByteBuffer()
//line views/vaudit/RecordDetail.html:64
	p.WriteBody(qb422016, as, ps)
//line views/vaudit/RecordDetail.html:64
	qs422016 := string(qb422016.B)
//line views/vaudit/RecordDetail.html:64
	qt422016.ReleaseByteBuffer(qb422016)
//line views/vaudit/RecordDetail.html:64
	return qs422016
//line views/vaudit/RecordDetail.html:64
}
